SCPS = {
	["SCP008"] = {
		model = "models/scp049/player/049zombie.mdl",
		swep = "fp_hands",
		maxhp = 1500,
		hp = 1200,
		scary = true,
		has_stamina = false,
		walkspeed = 210,
		crouchspeed = 0.5,
		slowwalkspeed = 85,
		jumppower = 175,
	},
	["SCP035"] = {
		model = "models/kutarum/brichevsk/scp_models/035.mdl",
		swep = "fp_hands",
		maxhp = 500,
		hp = 500,
		human = true,
		scale_damage = false,
		scary = false,
		has_stamina = false,
		walkspeed = 135,
		runspeed = 205,
		crouchspeed = 0.5,
		slowwalkspeed = 85,
		jumppower = 175,
	},
	["SCP096"] = {
		model = "models/washton/scp096/scp096unity.mdl",
		swep = "fp_scp_swep_096",
		maxhp = 2500,
		hp = 2500,
		scale_damage = false,
		scary = true,
		has_stamina = false,
		walkspeed = 120,
		crouchspeed = 0.5,
		slowwalkspeed = 85,
		jumppower = 125,
	},
}